(* ::Package:: *)

(* ::Input:: *)

(*SetOptions[EvaluationNotebook[],AutoGeneratedPackage->"TRACY.m"]*)

(* ::Title:: *)

(*TRACY -  Tracing Representations And Contractions Yourself*)

(* ::Section::Closed:: *)

(*Exports*)

(* ::Input::Initialization:: *)

FORMSimplify::usage = "FORMSimplify[expr]
FORMSimplify[expr, preReplRules, postReplRules]
Simplifies expressions using FORM's output optimization (O4) algorithms.
The first form uses default replacement rules for momentum expansion.
The second form allows specifying custom FORM preRepl and postRepl rules.
Integrates with FormTrace for powerful symbolic manipulation and optimization.
Essential for handling large expressions that benefit from FORM's optimization capabilities.";

SetAlwaysExpandLorentzTensors::usage = "";

IterativelySum::usage = "IterativelySum[list]
IterativelySum[list, finalSize]
Efficiently sums large lists of expressions by breaking them into subsets.
The first form repeatedly sums and simplifies until only a single expression remains.
The second form returns a list of specified finalSize with equally-sized terms.
Uses parallel processing and incremental simplification for optimal performance.
Crucial for managing memory and computation time in large symbolic calculations.";

FormMomentumExpansion::usage = "FormMomentumExpansion[]
FormMomentumExpansion[momenta...]
Creates a FORM rule to expand out any scalar products in expressions.
The optional momenta arguments specify which momenta to expand.
Can be passed as a postRepl or preRepl rule to FormTrace or FORMSimplify.
Essential for converting momentum-space expressions into expanded form for integration.";

FiniteTFormMomentumExpansion::usage = "FiniteTFormMomentumExpansion[]  
FiniteTFormMomentumExpansion[momenta...]
Creates a FORM rule to expand scalar products into spatial and temporal parts.
The optional momenta arguments specify which momenta to expand.
Separates d-dimensional momenta into (d-1)-dimensional spatial parts and time components.
Can be passed as a postRepl or preRepl rule to FormTrace or FORMSimplify.
Useful for finite-temperature field theory calculations.";

MakeP0Rule::usage = "MakeP0Rule[q, {p1, p2, ...}, {proj1, proj2, ...}]
Creates a replacement rule to project temporal components of momentum expressions.
The first argument q is the internal (loop) momentum variable.
The second argument is a list of external momenta {p1, p2, ...}.
The third argument is a list of projections {proj1, proj2, ...} for the temporal components.
Sets vec[pi,0] to the value of proji for finite-temperature field theory calculations.
Essential for evaluating expressions at specific temporal momentum projections.";

MakeP0FormRule::usage = "MakeP0FormRule[q, {p1, p2, ...}, {proj1, proj2, ...}]
Creates a FORM rule to project temporal components of momentum expressions.
The first argument q is the internal (loop) momentum variable.
The second argument is a list of external momenta {p1, p2, ...}.
The third argument is a list of projections {proj1, proj2, ...} for the temporal components.
Sets vec[pi,0] to the value of proji for finite-temperature field theory calculations.
Essential for evaluating expressions at specific temporal momentum projections.";

MakeSPFormRule::usage = "MakeSPFormRule[{l1, l2, ...}, p, {p1, p2, ...}]
Creates a FORM rule for symmetric point momentum configuration.
The first argument is a list of loop momenta {l1, l2, ...}.
The second argument p is the average momentum scale.
The third argument is a list of external leg momenta {p1, p2, ...}.
Projects all momenta to a symmetric configuration with average momentum p.
Crucial for evaluating loop integrals at the symmetric point for RG calculations.";

MakeSPFiniteTFormRule::usage = "MakeSPFiniteTFormRule[q, p, p1, p2, ...]
Creates a FORM rule for (d-1)-dimensional symmetric point configuration.
The first argument q is the internal (loop) momentum variable.
The second argument p is the average spatial momentum scale.
Remaining arguments are external leg momenta.
Projects momenta to spatial symmetric point configuration for finite-temperature calculations.
Separates temporal and spatial components for thermal field theory applications.";

ClearTraceCache::usage = "ClearTraceCache[]
ClearTraceCache[subdirectory]
Removes cached trace files from the trace cache directory.
The first form removes all files in the main trace cache (usually /tmp/TraceCache/).
The second form removes files from a specific subdirectory within the cache.
Use this to free up disk space or force recomputation of previously traced expressions.
Essential for cache management in long-running calculations.";

SetCacheDirectory::usage = "SetCacheDirectory[folder]
SetCacheDirectory[]
Changes the directory where traced expressions are cached.
The first form sets the cache directory to the specified folder path.
The second form resets the cache directory to the default /tmp/TraceCache/.
The cache directory stores intermediate results to avoid recomputation.
Per default, the cache directory is set to /tmp/TraceCache/.";

DiagramSimplify::usage = "DiagramSimplify[expr]
Simplifies diagrammatic expressions by collecting terms and optimizing their structure.
Uses advanced algorithms to identify common subexpressions and factor them efficiently.
Particularly effective for expressions with many coupling constants and similar terms.
Integrates with FORM's optimization capabilities when available for maximum efficiency.
Essential for making large diagrammatic calculations computationally manageable.";

(* ::Section:: *)

(*Begin Private*)

(* ::Input::Initialization:: *)

Begin["`Private`"]

ModuleLoaded::dependency = "The module `1` requires `2`, which has not been loaded.";

If[ModuleLoaded[FunKit] =!= True,
    Message[ModuleLoaded::dependency, "TRACY", "FunKit"];
    Abort[];
];

If[ModuleLoaded[FEDeriK] =!= True,
    Message[ModuleLoaded::dependency, "TRACY", "FEDeriK"];
    Abort[];
];

ModuleLoaded[TRACY] = True;

(* ::Section:: *)

(*Loading Components*)

(* ::Input::Initialization:: *)

(* Global setup *)

Get[$FunKitDirectory <> "modules/TRACY/Global.m"];

(* Cache *)

Get[$FunKitDirectory <> "modules/TRACY/Cache.m"];

(* FORM *)

Get[$FunKitDirectory <> "modules/TRACY/FORM.m"];

(* Tools *)

Get[$FunKitDirectory <> "modules/TRACY/Tools.m"];

(* Tracing *)

Get[$FunKitDirectory <> "modules/TRACY/Tracing.m"];

(* ::Section:: *)

(*End Private*)

(* ::Input::Initialization:: *)

End[]
