(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TensorBasesInstalled[]:=Module[{TensorBasesDirectory},
TensorBasesDirectory=SelectFirst[
Join[
{
FileNameJoin[{$UserBaseDirectory,"Applications","TensorBases"}],
FileNameJoin[{$BaseDirectory,"Applications","TensorBases"}],
FileNameJoin[{$InstallationDirectory,"AddOns","Applications","TensorBases"}],
FileNameJoin[{$InstallationDirectory,"AddOns","Packages","TensorBases"}],
FileNameJoin[{$InstallationDirectory,"AddOns","ExtraPackages","TensorBases"}]
},
Select[$Path,StringContainsQ[#,"TensorBases"]&]
],
DirectoryQ[#]&
]<>"/"//Quiet;
If[Head[TensorBasesDirectory]=!=String,Return[False]];
Return[True];
];

If[Not@TensorBasesInstalled[],
If[ChoiceDialog["\!\(\*
StyleBox[\"TensorBases\",\nFontWeight->\"Bold\"]\) does not seem to be installed. Do you want to install it?",WindowTitle->"Install \!\(\*
StyleBox[\"TensorBases\",\nFontWeight->\"Bold\"]\)",WindowSize->{Medium,All}],
Import["https://raw.githubusercontent.com/satfra/TensorBases/main/TensorBasesInstaller.m"],
Print["\!\(\*
StyleBox[\"FunKit\",\nFontWeight->\"Bold\"]\) requires \!\(\*
StyleBox[\"TensorBases\",\nFontWeight->\"Bold\"]\) to run."];Abort[];
];
];


(* ::Input::Initialization:: *)
$FunKitDirectory=SelectFirst[
Join[
{
FileNameJoin[{$UserBaseDirectory,"Applications","FunKit"}],
FileNameJoin[{$BaseDirectory,"Applications","FunKit"}],
FileNameJoin[{$InstallationDirectory,"AddOns","Applications","FunKit"}],
FileNameJoin[{$InstallationDirectory,"AddOns","Packages","FunKit"}],
FileNameJoin[{$InstallationDirectory,"AddOns","ExtraPackages","FunKit"}]
},
Select[$Path,StringContainsQ[#,"FunKit"]&]
],
DirectoryQ[#]&
]<>"/";


(* ::Input::Initialization:: *)
ModuleLoaded[FunKit]=True;


(* ::Input::Initialization:: *)
Print["\!\(\*
StyleBox[\"Loading\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"modules\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"...\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)"];
Block[{Print},Get["TensorBases`"]]
Print["\!\(\*
StyleBox[\"...\",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"TensorBases\",\nFontSize->10,\nFontWeight->\"Bold\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"loaded\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)"];
Get[$FunKitDirectory<>"modules/FEDeriK.m"];
Print["\!\(\*
StyleBox[\"...\",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"FEDeriK\",\nFontSize->10,\nFontWeight->\"Bold\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"loaded\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)"];
Get[$FunKitDirectory<>"modules/DiANE.m"];
Print["\!\(\*
StyleBox[\"...\",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"DiANE\",\nFontSize->10,\nFontWeight->\"Bold\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSize->10,\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"loaded\",\nFontSize->10,\nFontWeight->\"Plain\",\nFontSlant->\"Italic\"]\)"];

Print["Welcome to  \!\(\*
StyleBox[\"\:2588\:2580\",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\" \",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\"\:2590\:2584\:2588\",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\" \",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\"\:2588\:259a\:258c\",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\" \",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\"\:2590\[FilledLeftTriangle]\",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\" \",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\"\:2588\",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\" \",\nFontColor->GrayLevel[0]]\)\!\(\*
StyleBox[\"\:2580\:2588\:2580\",\nFontColor->GrayLevel[0]]\)
\!\(\*
StyleBox[\"Author\",\nFontWeight->\"Bold\"]\): Franz Richard Sattler
\!\(\*
StyleBox[\"Version\",\nFontWeight->\"Bold\"]\): 1.0
\!\(\*
StyleBox[\"Year\",\nFontWeight->\"Bold\"]\): 2025
For more information, call \!\(\*
StyleBox[\"FunKitInfo\",\nFontColor->RGBColor[1, 0.5, 0]]\)[]."]
