name: run-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup build and install
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
          WOLFRAM_SCRIPT: /opt/Wolfram/WolframEngine/bin/wolframscript
        run: |
          apt-get update
          apt-get install -y cmake make git
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE
          make install

      - name: Run tests
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
          WOLFRAM_SCRIPT: /opt/Wolfram/WolframEngine/bin/wolframscript
        run: |
          cd $GITHUB_WORKSPACE/build
          make test
          cat
