name: run-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: wolframresearch/wolframengine:latest
      options: --user root --privileged --init --ulimit core=-1

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup build and install
        run: |
          apt-get update
          apt-get install -y cmake make
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE
          make install

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          make test
