name: run-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: wolframresearch/wolframengine:latest
      options: --user root --privileged --init --ulimit core=-1

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup build and install
        run: |
          apt-get update
          apt-get install -y cmake make
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../FunKit
          make install
          cd ..

      - name: Run tests
        run: |
          cd build
          make test
